baseURL = "https://divyansh.net/"
languageCode = "en-us"
title = "Divyansh Tiwari"

[deployment]
[[deployment.targets]]
name = "prod"
URL = "s3://website-divyansh.net?region=ap-south-1"
cloudFrontDistributionID = "E2T22LBXQVGQ1S"

[module]
  [[module.imports]]
    path = "github.com/samrobbins85/hugo-developer-portfolio"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/css/uikit.min.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit.min.js"
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit-icons.min.js"

# navigation
[menu]

  [[menu.main]]
  name = "About"
  URL = "about"
  weight=1

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight=2


[params]
home = "Home"
# Metadata
description = "Divyansh Tiwari's Portfolio Website"
author = "Divyansh Tiwari"

  [params.contact]
  enable = true
  formAction = "https://formspree.io/f/mwpezabo"

  [params.footer]
  email = "divyanshtiwarijpr@gmail.com"
  address = "Jaipur, India"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "rainbow_dash"
    tabWidth = 4
